services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  imdb_app:
    # image: python:3.10
    build: ./imdb_app
    container_name: imdb_app
    working_dir: /usr/src/app
    volumes:
      - ./imdb_app:/usr/src/app
    command: >
      sh -c "
        pip install --no-cache-dir -r requirements.txt &&
        python api/app.py & 
        streamlit run main.py --server.port=8501 --server.address=0.0.0.0
      "
    ports:
      - "8501:8501" # Streamlit
      - "5000:5000" # Flask
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    restart: on-failure

volumes:
  postgres_data:
